### ISSUE TITLE
Detection Out-of-domain/Out-of-scope examples

### ISSUE THREAD

**Issue by petrLorenc** [bazingagin/npc_gzip#12]
I was not able to find that part in your code or explanation in your paper about detection od Out-of-domain/Out-of-scope examples. Was it some kind of thresholding?

**Comment by bazingagin** [comment]
Hi @petrLorenc, there is no OOD detection part in either the code or the paper. The OOD in our case mainly refers to those datasets that are not in English. So it's OOD w.r.t. pre-trained datasets used for BERT.
