### ISSUE TITLE
How to load a custom dataset

### ISSUE THREAD

**Issue by StudyingLover** [bazingagin/npc_gzip#15]
I made a set of my own data set, but I found that your code uses torchtext to load data, how to load my custom dataset

**Comment by bazingagin** [comment]
I've added the function and doc in the readme: https://github.com/bazingagin/npc_gzip#use-custom-dataset. Hope that helps.

**Comment by StudyingLover** [comment]
I think I need some help :tired_face: 
![image](https://github.com/bazingagin/npc_gzip/assets/68844494/797d794b-ef89-43b5-846e-fdf7017a8e61)
This  is my dir tree, data/custom is my custom data,then I run command
```
python main_text.py --data_dir data  --dataset custom     
```
I got a miskate 
```
Traceback (most recent call last):
  File "/home/npc_gzip/main_text.py", line 162, in <module>
    dataset_pair = eval(args.dataset)(root=args.data_dir)
  File "<string>", line 1, in <module>
NameError: name 'custom' is not defined
```
I wonder how to use

**Comment by StudyingLover** [comment]
Besides, I notice there are some mistakes caused by annotation ,https://github.com/bazingagin/npc_gzip/pull/22 ,I have fix them.

**Comment by bazingagin** [comment]
It should be fixed now. You can pass "custom" to "--dataset" with additional "--class_num" indicating the number of classes. Also according to your structure I think you should pass "data/custom" to "--data_dir".

**Comment by StudyingLover** [comment]
Oooooo! Thank you! That's a amazing work I think and I have run my custom data successfully !
