### ISSUE TITLE
slice of ohsumed dataset?

### ISSUE THREAD

**Issue by cyrilou242** [bazingagin/npc_gzip#17]
Hey, 

In the paper, the ohsumed dataset has 3.4k train and 4k test observations. 
From what I understood on hugging face https://huggingface.co/datasets/ohsumed and here http://disi.unitn.it/moschitti/corpora.htm the original dataset has way more observations.

Could you give more detail on how the dataset was obtained and where I can find it?

**Comment by bazingagin** [comment]
Sure. I used the data split from previous work: Yao, Liang, Chengsheng Mao, and Yuan Luo. "Graph convolutional networks for text classification." Proceedings of the AAAI conference on artificial intelligence. Vol. 33. No. 01. 2019.
<img width="722" alt="Screenshot 2023-07-23 at 7 07 08 PM" src="https://github.com/bazingagin/npc_gzip/assets/11184292/6a012eab-c43d-47b6-b21e-a4c4ee1382b2">

You can download here: https://github.com/yao8839836/text_gcn/tree/master/data/ohsumed_single_23

**Comment by cyrilou242** [comment]
Thanks @bazingagin !
