### ISSUE TITLE
Repository "About" description

### ISSUE THREAD

**Issue by EliahKagan** [bazingagin/npc_gzip#42]
I recommend adding a brief description of this project in the "About" metadata for the GitHub repository.

Once added, it will appear in place of the `No description, website, or topics provided.` message:

> ![Current About metadata](https://github.com/bazingagin/npc_gzip/assets/1771172/f1e529ba-ffa1-4e59-b73a-8742b81b7c06)

Only the repository owner can change this, and it's not determined by the files in the repository so I can't propose this with a pull request. But I'd suggest having it be:

> Code for Paper: “Low-Resource” Text Classification: A Parameter-Free Classification Method with Compressors

Since that text is both the top-level heading in the README and the `description` field in `pyproject.toml`.

**Comment by bazingagin** [comment]
Great call! Added.
