### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by EliahKagan** [bazingagin/npc_gzip#6]
I haven't noticed any information about how we're allowed to use, adapt, and redistribute this code.

If you're willing, I recommend [choosing a license](https://choosealicense.com/) and [adding a `LICENSE` file to the repository](https://docs.github.com/en/communities/setting-up-your-project-for-healthy-contributions/adding-a-license-to-a-repository) to indicate it.

(The [MIT license](https://choosealicense.com/licenses/mit/) is one popular choice, but I don't know what your preferences are.)

**Comment by bazingagin** [comment]
Great call! Just added MIT license.
