### ISSUE TITLE
pip install fails on deb and win

### ISSUE THREAD

**Issue by ras44** [bazingagin/npc_gzip#9]
Hi, thanks for sharing this!

I tried a relatively simple install process on a .deb system:

```
conda create -n npc python=3.8
conda activate npc
pip install -r requirements.txt
```

And it fails wtih:

```
libraries mkl_rt not found in ...
```

I've also tried installing the Intel MKV libraries, but no success

**Comment by StudyingLover** [comment]
I have download these requirements in Archlinux successfully, so I recommend you use **python==3.7**.

**Comment by ras44** [comment]
thanks @StudyingLover that works
